// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2HvDTjd5WRSqHOs604s9lQ1btd9qw2o',
    appId: '1:842227545035:web:3b68cc951e20f19ad0fc4e',
    messagingSenderId: '842227545035',
    projectId: 'queue-01-22',
    authDomain: 'queue-01-22.firebaseapp.com',
    databaseURL: 'https://queue-01-22-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'queue-01-22.appspot.com',
    measurementId: 'G-CTT8CQRV6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxOIPEwhNooJgFJiDHAGsk9D2Hc3fg0s',
    appId: '1:842227545035:android:57ddf8bec307baf3d0fc4e',
    messagingSenderId: '842227545035',
    projectId: 'queue-01-22',
    databaseURL: 'https://queue-01-22-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'queue-01-22.appspot.com',
  );
}
