name: Create Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check changelog
        uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: calver
          release_branch: main

      - name: Set version
        run: | 
          echo "VERSION = v${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.${{ steps.version.outputs.patch-version }}-pre" >> $GITHUB_ENV
          echo "Version is ${{ env.VERSION }}"

      - name: Install yq 
        run: brew install yq jq
            
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
          architecture: arm64

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: subdir/package-lock.json
          node-version: 20.14.0

      - name: Install firebase
        run: |
            npm install -g firebase-tools
            dart pub global activate flutterfire_cli
            flutterfire configure --token ${{ secrets.FIREBASE_TOKEN }} --platforms="android,ios,macos,web,windows" \
            -a  "com.glootea.queueminder" \
            -i  "com.glootea.queueminder" \
            -m  "com.glootea.queueminder" \
            -w  "${{ secrets.WEB_APP_ID }}" \
            -x  "${{ secrets.WINDOWS_APP_ID }}" 

      - name: Accept licenses
        run: flutter doctor --android-licenses


      - name: Setup and cache android      
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            ndk;25.1.8937393
            platforms;android-31
            platforms;android-32
          cache: true

      - name: Build 
        run: |
          flutter build apk --target-platform=android-arm64
#         flutter build ios --release --no-codesign
#         flutter build macos
#         flutter build web --wasm
      - uses: CupOfTea696/gh-action-auto-release@v1.0.0
        with:
          title: "Release: ${{ env.VERSION }}"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: ${{ env.VERSION }}
      #     files: |
      #       build/app/outputs/flutter-apk/app-release.apk
     